[tool.poetry]
name = "fastapi-hello-world"
version = "0.1.0"
description = "Hello World con FastAPI: CRUD simple en memoria"
authors = ["Your Name <your.email@example.com>"]
readme = "README.md"
packages = [{include = "app"}]
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.115.0"
python-multipart = "^0.0.20"
uvicorn = {extras = ["standard"], version = "^0.30.0"}
pydantic = "^2.9.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
